name: Publish

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - name: Install Node.js packages
        run: npm ci
      - name: Build
        run: ./build.sh
      - name: Test
        run: npm test
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
