name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Install Node.js packages
      run: npm ci
    - name: Build
      run: ./build.sh
    - name: Test
      run: npm test
